version: "3.8"

services:
  backend:
    image: tausifansar/todo-backend:latest
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always

  frontend:
    image: tausifansar/todo-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always